query AllTodos($input: allTodos_input) {
  allTodos(input: $input) {
    edges {
      node {
        id
        title
        description
        complete
        project {
          id
          title
        }
        createdAt {
          iso8601
        }
        completedAt {
          iso8601
        }
      }
    }
  }
}
